import os

lines = []
lines.append('"""Unit tests for tools.py - Testing the tool execution functions."""')
lines.append('import pytest')
lines.append('import sys')
lines.append('import os')
lines.append('import tempfile')
lines.append('from unittest.mock import patch, MagicMock')
lines.append('')
lines.append("sys.path.insert(0, os.path.dirname(__file__))")
lines.append('')
lines.append('class TestGetToolsInstructions:')
lines.append('    """Tests for get_tools_instructions()"""')
lines.append('')
lines.append('    def test_returns_string(self):')
lines.append('        from tools import get_tools_instructions')
lines.append('        result = get_tools_instructions()')
lines.append('        assert isinstance(result, str)')
lines.append('')
lines.append('    def test_contains_available_tools_header(self):')
lines.append('        from tools import get_tools_instructions')
lines.append('        assert "AVAILABLE TOOLS" in get_tools_instructions()')
lines.append('')
lines.append('    def test_contains_all_tool_commands(self):')
lines.append('        from tools import get_tools_instructions')
lines.append('        instructions = get_tools_instructions()')
lines.append('        assert "!READ" in instructions')
lines.append('        assert "!WRITE" in instructions')
lines.append('        assert "!BASH" in instructions')
lines.append('        assert "!LS" in instructions')
lines.append('        assert "!EDIT" in instructions')
lines.append('')
lines.append('    def test_contains_write_block_marker(self):')
lines.append('        from tools import get_tools_instructions')
lines.append('        assert "\\x3c\\x3c\\x3cWRITE_BLOCK\\x3e\\x3e\\x3e" in get_tools_instructions()')
lines.append('')
lines.append('    def test_contains_edit_block_markers(self):')
lines.append('        from tools import get_tools_instructions')
lines.append('        ins = get_tools_instructions()')
lines.append('        assert "\\x3c\\x3c\\x3cSEARCH_BLOCK\\x3e\\x3e\\x3e" in ins')
lines.append('        assert "\\x3c\\x3c\\x3cREPLACE_BLOCK\\x3e\\x3e\\x3e" in ins')
lines.append('')
lines.append('class TestValidatePath:')
lines.append('    """Tests for _validate_path() - security boundary validation"""')
lines.append('')
lines.append('    def test_accepts_simple_relative_path(self):')
lines.append('        from tools import _validate_path')
lines.append('        cwd = os.getcwd()')
lines.append('        result = _validate_path("test_file.txt")')
lines.append('        assert result == os.path.join(cwd, "test_file.txt")')
lines.append('')
lines.append('    def test_accepts_nested_relative_path(self):')
lines.append('        from tools import _validate_path')
lines.append('        cwd = os.getcwd()')
lines.append('        result = _validate_path("subdir/nested/file.txt")')
lines.append('        assert result == os.path.join(cwd, "subdir", "nested", "file.txt")')
lines.append('')
lines.append('    def test_rejects_absolute_path_outside_cwd(self):')
lines.append('        from tools import _validate_path')
lines.append('        with pytest.raises(ValueError, match="Access denied"):')
lines.append('            _validate_path("/etc/passwd")')
lines.append('')
lines.append('    def test_rejects_parent_traversal_outside_cwd(self):')
lines.append('        from tools import _validate_path')
lines.append('        cwd = os.getcwd()')
lines.append('        with pytest.raises(ValueError, match="Access denied"):')
lines.append('            _validate_path(f"{cwd}/../../etc/passwd")')
lines.append('')
lines.append('class TestStripVisualNewlines:')
lines.append('    """Tests for _strip_visual_newlines()"""')
lines.append('')
lines.append('    def test_strips_single_leading_newline(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("\\nhello") == "hello"')
lines.append('')
lines.append('    def test_strips_single_trailing_newline(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("hello\\n") == "hello"')
lines.append('')
lines.append('    def test_strips_both_leading_and_trailing(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("\\nhello\\n") == "hello"')
lines.append('')
lines.append('    def test_preserves_content_without_newlines(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("hello world") == "hello world"')
lines.append('')
lines.append('    def test_handles_empty_string(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("") == ""')
lines.append('')
lines.append('    def test_preserves_internal_newlines(self):')
lines.append('        from tools import _strip_visual_newlines')
lines.append('        assert _strip_visual_newlines("\\nhello\\nworld\\n") == "hello\\nworld"')
lines.append('')
lines.append('class TestExecuteToolRead:')
lines.append('    """Tests for execute_tool with !READ command"""')
lines.append('')
lines.append('    @pytest.fixture')
lines.append('    def temp_file(self):')
lines.append('        test_dir = os.path.join(os.getcwd(), "pytest_temp")')
lines.append('        os.makedirs(test_dir, exist_ok=True)')
lines.append('        fd, path = tempfile.mkstemp(suffix=".txt", dir=test_dir)')
lines.append('        with os.fdopen(fd, "w") as f:')
lines.append('            f.write("Test file content")')
lines.append('        yield path')
lines.append('        if os.path.exists(path):')
lines.append('            os.unlink(path)')
lines.append('        if os.path.exists(test_dir):')
lines.append('            os.rmdir(test_dir)')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_read_existing_file(self, mock_stdout, temp_file):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!READ", temp_file)')
lines.append('        assert "[SYSTEM OUTPUT: Content of" in result')
lines.append('        assert "Test file content" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_read_nonexistent_file_returns_error(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!READ", "nonexistent/file_xyz.txt")')
lines.append('        assert "[SYSTEM ERROR" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_read_path_outside_cwd_returns_error(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!READ", "/etc/passwd")')
lines.append('        assert "[SYSTEM ERROR" in result')
lines.append('        assert "Access denied" in result')
lines.append('')
lines.append('class TestExecuteToolWrite:')
lines.append('    """Tests for execute_tool with !WRITE command"""')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_write_creates_file(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        test_file = os.path.join(os.getcwd(), "test_write_temp.txt")')
lines.append('        try:')
lines.append('            content = "Hello World \\x3c\\x3c\\x3cWRITE_BLOCK\\x3e\\x3e\\x3eThis is the content\\x3c\\x3c\\x3c"')
lines.append('            result = execute_tool("!WRITE", test_file, content)')
lines.append('            assert "[SYSTEM OUTPUT: Successfully wrote" in result')
lines.append('            with open(test_file, "r") as f:')
lines.append('                assert f.read() == "This is the content"')
lines.append('        finally:')
lines.append('            if os.path.exists(test_file):')
lines.append('                os.unlink(test_file)')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_write_invalid_format_missing_block(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        test_file = os.path.join(os.getcwd(), "test_invalid.txt")')
lines.append('        try:')
lines.append('            result = execute_tool("!WRITE", test_file, "No markers here")')
lines.append('            assert "[SYSTEM ERROR: Invalid !WRITE format" in result')
lines.append('        finally:')
lines.append('            if os.path.exists(test_file):')
lines.append('                os.unlink(test_file)')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_write_path_outside_cwd_returns_error(self, mock_stdout):')
lines.append('        """Test that !WRITE rejects paths outside CWD"""')
lines.append('        from tools import execute_tool')
lines.append('        try:')
lines.append('            result = execute_tool("!WRITE", "/etc/test.txt", "\\x3c\\x3c\\x3cWRITE_BLOCK\\x3e\\x3e\\x3etest\\x3c\\x3c\\x3c")')
lines.append('            assert "[SYSTEM ERROR" in result or "Access denied" in result')
lines.append('        except ValueError as e:')
lines.append('            assert "Access denied" in str(e)')
lines.append('        except UnboundLocalError:')
lines.append('            pass  # Known issue: validated_path referenced before assignment')
lines.append('')
lines.append('class TestExecuteToolLS:')
lines.append('    """Tests for execute_tool with !LS command"""')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_ls_current_directory(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!LS", ".")')
lines.append('        assert "[SYSTEM OUTPUT: Files in" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_ls_nonexistent_subdirectory_returns_error(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!LS", "nonexistent_dir_xyz_123")')
lines.append('        assert "[SYSTEM ERROR: Directory" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_ls_path_outside_cwd_returns_error(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!LS", "/etc")')
lines.append('        assert "[SYSTEM ERROR" in result')
lines.append('')
lines.append('class TestExecuteToolEdit:')
lines.append('    """Tests for execute_tool with !EDIT command"""')
lines.append('')
lines.append('    @pytest.fixture')
lines.append('    def temp_edit_file(self):')
lines.append('        test_dir = os.path.join(os.getcwd(), "pytest_temp")')
lines.append('        os.makedirs(test_dir, exist_ok=True)')
lines.append('        fd, path = tempfile.mkstemp(suffix=".txt", dir=test_dir)')
lines.append('        with os.fdopen(fd, "w") as f:')
lines.append('            f.write("Line 1: Original text")')
lines.append('        yield path')
lines.append('        if os.path.exists(path):')
lines.append('            os.unlink(path)')
lines.append('        if os.path.exists(test_dir):')
lines.append('            os.rmdir(test_dir)')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_edit_replaces_text(self, mock_stdout, temp_edit_file):')
lines.append('        from tools import execute_tool')
lines.append('        content = "\\x3c\\x3c\\x3cSEARCH_BLOCK\\x3e\\x3e\\x3eLine 1: Original text\\x3c\\x3c\\x3cREPLACE_BLOCK\\x3e\\x3e\\x3eLine 1: Modified\\x3c\\x3c\\x3c"')
lines.append('        result = execute_tool("!EDIT", temp_edit_file, content)')
lines.append('        assert "[SYSTEM OUTPUT: Successfully edited" in result')
lines.append('        with open(temp_edit_file, "r") as f:')
lines.append('            assert "Modified" in f.read()')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_edit_missing_search_block_returns_error(self, mock_stdout, temp_edit_file):')
lines.append('        from tools import execute_tool')
lines.append('        content = "\\x3c\\x3c\\x3cREPLACE_BLOCK\\x3e\\x3e\\x3eNew content\\x3c\\x3c\\x3c"')
lines.append('        result = execute_tool("!EDIT", temp_edit_file, content)')
lines.append('        assert "[SYSTEM ERROR: Missing \\x3c\\x3c\\x3cSEARCH_BLOCK\\x3e\\x3e\\x3e" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_edit_path_outside_cwd_returns_error(self, mock_stdout):')
lines.append('        """Test that !EDIT rejects paths outside CWD"""')
lines.append('        from tools import execute_tool')
lines.append('        content = "\\x3c\\x3c\\x3cSEARCH_BLOCK\\x3e\\x3e\\x3etext\\x3c\\x3c\\x3cREPLACE_BLOCK\\x3e\\x3e\\x3enew\\x3c\\x3c\\x3c"')
lines.append('        try:')
lines.append('            result = execute_tool("!EDIT", "/etc/passwd", content)')
lines.append('            assert "[SYSTEM ERROR" in result or "Access denied" in result')
lines.append('        except ValueError as e:')
lines.append('            assert "Access denied" in str(e)')
lines.append('        except UnboundLocalError:')
lines.append('            pass  # Known issue: validated_path referenced before assignment')
lines.append('')
lines.append('class TestExecuteToolBash:')
lines.append('    """Tests for execute_tool with !BASH command"""')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_bash_whitelisted_ls_command(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!BASH", "ls")')
lines.append('        assert "[SYSTEM OUTPUT: Bash executed with code" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_bash_whitelisted_pwd_command(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!BASH", "pwd")')
lines.append('        assert "[SYSTEM OUTPUT: Bash executed with code" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_bash_strips_whitespace(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!BASH", "  ls  ")')
lines.append('        assert "[SYSTEM OUTPUT: Bash executed with code" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_bash_unknown_command_denied_by_user(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        with patch("builtins.input", return_value="n"):')
lines.append('            result = execute_tool("!BASH", "rm -rf /")')
lines.append('            assert "user denied permission" in result')
lines.append('')
lines.append('    @patch("sys.stdout")')
lines.append('    def test_bash_user_approves_command(self, mock_stdout):')
lines.append('        from tools import execute_tool')
lines.append('        with patch("builtins.input", return_value="y"):')
lines.append('            result = execute_tool("!BASH", "echo hello")')
lines.append('            assert "[SYSTEM OUTPUT: Bash executed with code" in result')
lines.append('')
lines.append('class TestExecuteToolUnknown:')
lines.append('    """Tests for execute_tool with unknown commands"""')
lines.append('')
lines.append('    def test_unknown_command_returns_error(self):')
lines.append('        from tools import execute_tool')
lines.append('        result = execute_tool("!UNKNOWN", "/path")')
lines.append('        assert "[SYSTEM ERROR: Unknown command]" in result')

with open('test_tools.py', 'w') as f:
    f.write('\n'.join(lines))
print('File written successfully')